[project]
name = "chainlit-ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.8.1",
    "openai-agents>=0.3.2",
    "speedtest>=0.0.1",
]
