[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.8.1",
    "mcp>=1.15.0",
    "ollama>=0.6.0",
    "openai-agents>=0.3.2",
    "pypdf2>=3.0.1",
]
